services:
  service:
    image: service
    build:
      context: .
      dockerfile: Service/Dockerfile
      
  postgres:
    image: postgres:17-bullseye
    ports:
      - 46005:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TimeTracking