name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:

  build:

    environment: TimeTrackingDocker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      uses: docker/login-action@v3.7.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.TOKEN }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag time_tracking:$(date +%s)

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
      uses: docker/build-push-action@v6.19.2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ghcr.io/${{ github.repository }}:latest

              
